### PR TITLE
Canvas fix

### LINKED ISSUE #17: canvas resolution is configurable via slider
the canvas could be displayed at different sizes.

we want to represent resolution in terms of a slider, from 10% to 100% -- the actual rendering resolution should be some percentage of the actual canvas dimensions

- let's say canvas is 1000x500 pixels in actual dimensions on the web page
- the resolution slider is at 50%
- the actual canvas rendering resolution should then be 500x250 (half the displayed width/height on the webpage)

### LINKED ISSUE #21: theater canvas resolution is incorrect when view mode changes

### LINKED ISSUE #24: theater view mode icon is wrong when exiting fullscreen via escape key

### PR DESCRIPTION
**Pull request by zenkyuv**
closes #24, #21, #17

### CODE REVIEW

File: s/babylon/theater/utils/make-babylon-world.ts [hunk 1]
```diff
@@ -46,11 +46,11 @@ export function makeBabylonWorld(): BabylonWorld {
 		renderLoop,
 		sceneInstrumentation,
 		engineInstrumentation,
-		resize() {
+		resize(res) {
```
Comment (PaulAroo) [inline s/babylon/theater/utils/make-babylon-world.ts:49]: something minor, but maybe this could be fully named? `resolution`

**Review by PaulAroo — COMMENTED** [review]
Great work @zenkyuv 
using resize observers is so much better, tested it and it works well 👍🏽

File: s/babylon/theater/utils/make-babylon-world.ts (hunk 1 above)
Comment (zenkyuv) [reply s/babylon/theater/utils/make-babylon-world.ts:49]: Yeah i think it would be better to use full name here, im starting to realize it more, its only better to use shortands only for obvious things i think ..

Comment (PaulAroo) [reply s/babylon/theater/utils/make-babylon-world.ts:49]: yeah
the classic is `e` for `event`, when writing event listeners 😅
